apiVersion: v1
kind: Pod
metadata:
  name: vulnerable-app
  labels:
    app: vulnerable-app
spec:
  containers:
  - name: vulnerable-container
    image: node:22.6.0 # Docker con vulnerabilidades
    ports:
    - containerPort: 3000 # Habilitar puerto de la API
    env:
    - name: ENV_VAR
      value: "sensitive_data" # Información sensible en variables de entorno
    - name: API_KEY
      value: "insecure-api-key" # API key expuesta
    securityContext:
      runAsUser: 0 # Ejecutar como root
      capabilities:
        add: ["SYS_ADMIN"] # Capacidades adicionales innecesarias
    volumeMounts:
    - name: sensitive-volume
      mountPath: /data
  volumes:
  - name: sensitive-volume
    hostPath:
      path: /etc # Montaje de directorio sensible del host
