name: Snyk IaC
on:
  pull_request:
    branches: ["main", "qa", "dev"]
jobs:
    security:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Run Snyk to check Kubernetes manifest file for issues
              uses: snyk/actions/iac@master
              env:
                SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
              with:
                args: --report
            - name: Upload result to GitHub Code Scanning
              uses: github/codeql-action/upload-sarif@v3
              with:
                sarif_file: snyk.sarif              
