name: ZAP API Scan

on:
  pull_request:
    branches: [ "main", "qa", "dev" ]

jobs:
    zap_scan:
        runs-on: self-hosted
        permissions:
            contents: write
            pull-requests: write
            repository-projects: write
        steps:
            - uses: actions/checkout@v4
            - name: Build a Docker image
              run: docker build -t tfm/app .
            - name: Initialize API container
              run: docker run -d --name tfm_app -p 3000:3000 tfm/app

            - name: Wait for API to start
              run: sleep 10

            - name: Run ZAP API scan
              uses: zaproxy/action-api-scan@v0.7.0
              with:
                token: ${{ secrets.ZAP_TOKEN }}
                format: openapi
                target: 'http://localhost:3000/api'
                cmd_options: '-a'
              continue-on-error: true
            
            - name: Stop and remove API container
              run: docker stop tfm_app && docker rm tfm_app

            - name: Remove Docker image
              run: docker rmi tfm/app
        
            - name: Upload ZAP report
              uses: actions/upload-artifact@v4
              with: 
                name: zap_report
                path: zap_report.html
              continue-on-error: true